go_import_path: github.com/akutz/golf
language: go
go:
  - 1.7.5
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - curl -sSLO https://github.com/Masterminds/glide/releases/download/v0.11.1/glide-v0.11.1-linux-amd64.tar.gz
  - tar xzf glide-v0.11.1-linux-amd64.tar.gz
  - mkdir -p $GOPATH/bin && mv linux-amd64/glide $GOPATH/bin
  - rm -fr glide-v0.11.1-linux-amd64.tar.gz linux-amd64
install:
  - glide install
script:
  - go install $(glide nv)
  - go test $(glide nv)
  - goveralls -service=travis-ci
